# Generated by Django 4.1.1 on 2023-09-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hngx_stage2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='country_residence',
        ),
        migrations.RemoveField(
            model_name='person',
            name='state_residence',
        ),
    ]
